### ISSUE TITLE
#15 FloripaJS Devs Meetup – Segware

### ISSUE THREAD

**Issue by diogomoretti** [floripajs/talks#1]
Cada comentário será uma talk. O pessoal vota apenas usando o 👍 

FORMATO

```markdown
**Título**:
**Descrição**:
**Comentário (opcional)**:
```

**DATA LIMITE PARA SUBMISSÃO:** 01/Junho/2017 – 20h

=]

**Comment by bernardocs** [comment]
## Modern Layout Development
Showcase de features comumente (ou que serão) utilizadas para desenvolver layouts nos dias atuais. Além de algumas dicas de como não se enrolar no aprendizado das mesmas.

**Comment by vinicius0026** [comment]
**Título**: Introdução ao Vue.js
**Descrição**: Introdução ao Vue.js com foco em SPAs, apresentado as ferramentas que compõem o ecossistema Vue, tais como vue-router, vuex e axios, além de algumas bibliotecas para UI.

**Comment by bateramos** [comment]
**Título**: Serverless and How to create your own Serverless with node.js
**Descrição**: Introdução a Serverless, principais providers e frameworks, o que node.js tem a ver com isso, oportunidades, desafios, demo de um "Serverless" rodando localmente.
**Comentário (opcional)**: repo da demo https://github.com/bateramos/docker-swarm-deploy-demo

**Comment by sebas5384** [comment]
**Título:** Vacinando mais de 200mil pessoas com ReactJS e GraphQL
**Descrição:** Case de sucesso do projeto de Vacinação do SESI - FIESC em Santa Catarina onde foi usado ReactJS com GraphQL no front e Drupal no backend. Parte do sucesso deste projeto foi graças ao stack de Javascript que foi utilizado, possibilitando criar um frontend modular e em constante crescimento.
Gostaria de mostrar quais bibliotecas usamos, como e porque foram utilizadas.
Entre elas, o [React](https://facebook.github.io/react/), [Recompose](https://github.com/acdlite/recompose), [CSS Modules](https://github.com/css-modules/css-modules), [Redux Boot](https://github.com/choko-org/redux-boot), [GraphQL](https://github.com/graphql/graphql-js) com [Apollo Client](https://github.com/apollographql/apollo-client), [GraphQL Modules](https://github.com/lucasconstantino/graphql-modules), [Jest](https://facebook.github.io/jest/),  [NightwatchJS](http://nightwatchjs.org/) e [Webpack](https://webpack.js.org/).
**Comentário (opcional):** Pretendo focar na experiência que obtivemos no decorrer do desenvolvimento do projeto (e não em jabá).

**Comment by lucasfcosta** [comment]
Olá, amigos, sendo assim, @sebas5384, @bateramos e @bernardocs irão falar no próximo Meetup.

Valeu pela participação, no próximo tem mais 😄
