### ISSUE TITLE
#20 FloripaJS Devs Meetup - Dígitro

### ISSUE THREAD

**Issue by marquinhoalm** [floripajs/talks#10]
E aí pessoal! Está aberto o Call for Papers para as talks do próximo FloripaJS!

Dessa vez peço encarecidamente que não esqueçam de colocar o tempo das suas talks!

Basta seguir o template de resposta ao responder essa issue.

```
# [Título da sua talk (OBRIGATÓRIO)]

### Abstract

[Um parágrafo resumindo o conteúdo geral da sua talk. (OBRIGATÓRIO)]

### Descrição

[Uma descrição mais detalhada do que você vai falar, como vai ser seu approach ao assunto e coisas do tipo. (OPCIONAL)]

### Duração

[Tempo aproximado de duração da sua talk. (OBRIGATÓRIO)]

[Obs.: Não importa quanto tempo seja, desde que possua menos de 50/60 minutos. Encaixaremos as talks conforme a disponibilidade do horário.]

### Comentários

[Seus comentários sobre essa submissão. O motivo pelo qual você quer falar sobre isso ou o motivo pelo qual esse assunto é interessante. Enfim, tudo mais que você quiser falar. (OPCIONAL)]
```

**Datas**

**Prazo para envio:** 10/Abr/2018 - 23h
**Divulgação das talks aprovadas:** 11/Abr/2018 - 15h

**Comment by brunosfreitas** [comment]
#Fast Talk: Design para não designers (ou quase 15 ferramentas em quase 15 minutos)

###Abstract

Não sabe diferenciar vermelho de magenta? Está na dúvida do porque Comic Sans não fica bom com Times New Roman? Porque diabos o cliente quer o site dele marrom? O Designer do time (que nem existe, porque a grana está curta) foi viajar? Como resolver, ou pelo menos ter para onde correr, nessas horas?

### Descrição

A ideia é apresentar algumas ferramentas e sites que podem agilizar todo esse processo.
O que não fazer, ou tentar evitar, durante a montagem do seu sistema.

##Duração

(quase) 15 minutos.

## Comentários

Desperte o designer dentro de você! Essa apresentação serve como base para qualquer um que deseja aprender uma base mínima de como sobreviver com dicas de design prático, não sendo focada somente para devs.

**Comment by jaburcodes** [comment]
# React-Native animations

### Abstract
Apresentação dos métodos mais usuais para construir animações em aplicações mobile(react-native)

### Descrição

A talk vai ser dividida em duas partes,

Na primeira seção vou mostrar as ferramentas/métodos mais usuais no mercado e descrever a importância de animations na sua aplicação em termos de UX.

Na segunda e última faremos uma live coding session para que eu possa mostrar que escrever animações pode ser rápido e simples.

### Duração
40 minutos

**Comment by diogomoretti** [comment]
Obrigado a todos que submeteram!
