### ISSUE TITLE
#21 FloripaJS Devs Meetup - Segware 

### ISSUE THREAD

**Issue by diogomoretti** [floripajs/talks#11]
Bora submeter sua talk para mais um FloripaJS!

Dessa vez escolheremos apenas *01 TALK*, pois a grade será completa no dia no formato `Hack n' Tell` (Saiba mais do formato aqui http://hackntell.floripajs.org)

Link do Meetup: https://www.meetup.com/floripajs/events/253379592/

```
# [Título da sua talk (OBRIGATÓRIO)]

### Abstract

[Um parágrafo resumindo o conteúdo geral da sua talk. (OBRIGATÓRIO)]

### Descrição

[Uma descrição mais detalhada do que você vai falar, como vai ser seu approach ao assunto e coisas do tipo. (OPCIONAL)]

### Duração

[Tempo aproximado de duração da sua talk. (OBRIGATÓRIO)]

[Obs.: Não importa quanto tempo seja, desde que possua menos de 50/60 minutos. Encaixaremos as talks conforme a disponibilidade do horário.]

### Comentários

[Seus comentários sobre essa submissão. O motivo pelo qual você quer falar sobre isso ou o motivo pelo qual esse assunto é interessante. Enfim, tudo mais que você quiser falar. (OPCIONAL)]
```

**Datas**

**Prazo para envio:** 15/Ago/2018 - 23h
**Divulgação das talks aprovadas:** 16/Ago/2018 - 11h

**Comment by caian-gums** [comment]
Olá, eu estava pensando em submeter uma Talk mas estou com algumas dúvidas e podem ser dúvidas de outras pessoas também. Como não quero parecer uma pessoa ruim que só encontra problemas, vou dar algumas sugestões do que pode ser feito para talvez solucionar. Fica a critério da organização optar pela forma que considerar melhor.

1. As talks no formato `Hack'n'Tell` serão submetidas no dia?

Alguns problemas que eu consigo ressaltar dessa abordagem é: O formato `Hack'n'Tell` foi feito para encontros entre 8-10 pessoas onde todos terão a oportunidade de falar um pouco sobre alguma coisa. Teoricamente todos podem dar alguma ideia ou falar sobre algo e discutem sobre isso. Em um evento maior isso começa a ficar inviável visto que quanto mais pessoas, mais Talks.

Minha sugestão é permitir que a comunidade submeta Talks curtas(10min) previamente e aconteça algum tipo de seleção, mas no dia ainda existam 'slots' abertos para talks que chegaram no dia, incentivando aqueles que não tiveram chance submeter ou submeteram e não foram aceitos.

2. O que vai ser disponibilizado pelo Evento para a apresentação?

Seria interessante comentar sobre o que vai estar disponível no local para as Talks como por exemplo: Projetor, Cabo HDMI, Tomadas, Computador(?), Conexão com Internet...

Talvez comentar sobre isso seja interessante na descrição do Evento no Meetup ou aqui mesmo. Se tiver que optar por um lugar só, eu sugiro deixar aqui apenas pois é aqui que as pessoas vão submeter a Talk.

3. Qual será o critério de seleção das Talks curtas no dia? Isso não está claro.

Caso os Organizadores possam observar os temas e ver se tem coerência com o evento previamente como é feito para a Talk de 40min isso poderia ser resolvido mas da maneira que está fica muito aberto e podem acontecer talks interessantes e inovadoras sendo deixadas de lado em virtude de talks sobre temas já batidos ou recorrentes.

Minha proposta para resolver isso é algo que eu sugeri antes: **Aceitar talks curtas(10min) antes do prazo e caso não sejam preenchidas escolher no dia por algum critério**. Pode ser ordem de chegada, mas deve estar **explícito** para não haver nenhum desentendimento. Não se pode agradar a todos mas pode-se tentar agradar o máximo número de pessoas possível dentro do que é possível ser feito.


No mais, eu gostaria de submeter uma talk mas ela não é grande o suficiente para 40 minutos. Ficaria um pouco frustrado de chegar no dia preparado com tudo e não poder falar sendo que talvez alguém faça uma talk sobre um tema completamente fora do escopo do evento e ele foi escolhido sem nenhum critério. Se o critério de escolha for explicitamente `Hora de Submissão no Dia` eu me esforçarei para chegar o mais cedo possível e inscrever minha Talk mas não saber qual é o Critério torna caótico e pode gerar frustração de outras pessoas.

**Comment by diogomoretti** [comment]
@caian-gums vou relatar no meetup.com! Abraços.
