### ISSUE TITLE
#22 FloripaJS Devs Meetup - Softplan

### ISSUE THREAD

**Issue by diogomoretti** [floripajs/talks#12]
Bora submeter sua talk para mais um FloripaJS!

Dessa vez escolheremos no máximo *02 TALKS* e o resto da grade será composta pelo formato `Hack n' Tell` (Saiba mais do formato aqui http://hackntell.floripajs.org)

Link do Meetup: https://www.meetup.com/floripajs/events/258699854

```
# [Título da sua talk (OBRIGATÓRIO)]

### Abstract

[Um parágrafo resumindo o conteúdo geral da sua talk. (OBRIGATÓRIO)]

### Descrição

[Uma descrição mais detalhada do que você vai falar, como vai ser seu approach ao assunto e coisas do tipo. (OPCIONAL)]

### Duração

[Tempo aproximado de duração da sua talk. (OBRIGATÓRIO)]

[Obs.: Não importa quanto tempo seja, desde que possua menos de 50/60 minutos. Encaixaremos as talks conforme a disponibilidade do horário.]

### Comentários

[Seus comentários sobre essa submissão. O motivo pelo qual você quer falar sobre isso ou o motivo pelo qual esse assunto é interessante. Enfim, tudo mais que você quiser falar. (OPCIONAL)]
```

A votação vocês já sabem, usar apenas o 👍

**Prazo para envio:** 13/Fev/2018 - 23h

**Comment by klarkc** [comment]
# BDD com o jest-cucumber

### Abstract

Vamos escrever uma história com um cenário e escrever os testes automatizados o jest-cucumber

### Descrição

A ideia é mostrar como chegamos da concepção de uma história ao código escrito de forma resumida e prática.

### Duração

30 min

### Comentários

Quero aprender mais sobre BDD e testes automatizados, ter feedback de outros devs como eles escrevem testes os critérios de aceite das histórias e compartilhar conhecimento!

**Comment by katesclau** [comment]
# OpenAPI vs GraphQL? OpenAPI ❤️ GraphQL

### Abstract
O que o REST do mundo tem a ver com GraphQL? Vamos brincar com ferramentas para tornar sua migração do OpenAPI/Swagger para GraphQL mais fácil 😉

### Descrição
Um passeio na toolchain de geração, consumo e conversão OAS 🔛 GraphQL

- [OpenAPI to Postman collections](https://github.com/postmanlabs/openapi-to-postman)
- [OpenAPI to GraphQL translator](https://github.com/strongloop/oasgraph)
- [OpenAPI Client Generator](https://github.com/OpenAPITools/openapi-generator)
_E tem mais..._ Prisma.io, e uma breve descrição pra quem ta perdido no mar 🌊 

### Duração

45 min

### Comentários

Esta talk é um apanhado dos perrengues que andei passando nos últimos meses pra integrar uma API OAS em um mundo de GraphQL 😅 - _fun_

**Comment by odahcam** [comment]
# Free NPM registry with Verdaccio and AWS

### Abstract

Quem nunca quis o seu pacotinho privado no NPM? A gente é open source mas nem sempre né. Nessa talk eu falo um pouquinho sobre como conseguir o seu registro de pacotes node privados de forma fácil e utilizando tecnologias que "estão na mídia". O principal mocinho nessa história é o Verdaccio, sobre o qual vou tagarelar um pouquinho e o coadjuvante é a AWS e seu serviço EC2.

### Descrição

- `helloFloripa()`
- Motivação.
- Como é possível obter um registro privado de pacotes node de gratis.
- Quem são as ferramentas da vez.
- Um pouco sobre a história e o que faz o Verdaccio.
- Explicando o passo a passo com exemplos.
- "live config-ing" (?!) tipo live coding, se possível.
- Perguntas?

### Duração

15min ~ 30min (conforme disponibilidade)

### Comentários

Notei que esse assunto despertou o interesse da galera, assim como eu sempre tive. Além de ser inicialmente de graça, o assunto aborda de uma forma amigável ferramentas como a AWS e permite que qualquer um com pouquíssimo conhecimento consiga alcançar o objetivo final da talk, abrindo caminho para explorar as ferramentas, tanto Verdaccio como AWS. E se for legal depois tem mais sobre, hehe.

**Comment by diogomoretti** [comment]
Já temos as duas talks: @klarkc e @odahcam. Tudo certo para sábado pessoal?

**Comment by klarkc** [comment]
tudo certo
