### ISSUE TITLE
#25 FloripaJS Devs Meetup – Involves

### ISSUE THREAD

**Issue by diogomoretti** [floripajs/talks#14]
Bora submeter sua talk para mais um FloripaJS!

Dessa vez escolheremos no máximo *02 TALKS* e o resto da grade será composta pelo formato `Hack n' Tell` (Saiba mais do formato aqui http://hackntell.floripajs.org)

Link do Meetup: https://www.meetup.com/floripajs/events/265094805

```
# [Título da sua talk (OBRIGATÓRIO)]

### Abstract

[Um parágrafo resumindo o conteúdo geral da sua talk. (OBRIGATÓRIO)]

### Descrição

[Uma descrição mais detalhada do que você vai falar, como vai ser seu approach ao assunto e coisas do tipo. (OPCIONAL)]

### Duração

[Tempo aproximado de duração da sua talk. (OBRIGATÓRIO)]

[Obs.: Não importa quanto tempo seja, desde que possua menos de 50/60 minutos. Encaixaremos as talks conforme a disponibilidade do horário.]

### Comentários

[Seus comentários sobre essa submissão. O motivo pelo qual você quer falar sobre isso ou o motivo pelo qual esse assunto é interessante. Enfim, tudo mais que você quiser falar. (OPCIONAL)]
```

A votação vocês já sabem, usar apenas o 👍

**Prazo para envio:** 01/Out/2019 - 23h

**Comment by marcobarbosa** [comment]
# Sneaky Santa

### Abstract
Por trás das cenas de uma idéia natalina despretenciosa que ser tornou em um projeto vencedor de prêmios.

### Descrição
Sneaky Santa é um projeto interno da 14islands que surgiu como um cartão natalino que fazemos todos os anos para amigos e clientes. Nesse ano (2019) a coisa foi um pouco além e eu gostaria de compartilhar como foi todo o processo do início ao fim.

### Duração
30 minutos.

### Comentários
Acho interessante mostrar esse projeto como inspiração para outras pessoas e empresas. A oportunidade de ter um momento de "hack" que acaba se tornando em um projeto mais organizado pode ser bem benéfica e vale reflexão.
