### ISSUE TITLE
Sneaky Santa

### ISSUE THREAD

**Issue by marcobarbosa** [floripajs/talks#15]
# Sneaky Santa

### Descrição

Sneaky Santa é um projeto interno que surgiu como um cartão natalino que fazemos todos os anos para amigos e clientes. Nesse ano (2019) a coisa foi um pouco além e eu gostaria de compartilhar como foi todo o processo do início ao fim.

### Duração

30 minutos.

### Comentários

Acho interessante mostrar esse projeto como inspiração para outras pessoas e empresas. A oportunidade de ter um momento de "hack" que acaba se tornando em um projeto mais organizado pode ser bem benéfica e vale reflexão.

**Comment by diogomoretti** [comment]
@marcobarbosa você deve responder a issue do meetup
