### ISSUE TITLE
#16 FloripaJS Devs Meetup – Dígitro

### ISSUE THREAD

**Issue by lucasfcosta** [floripajs/talks#2]
E aí pessoal! **Está aberto o Call for Papers para as talks do próximo FloripaJS!**

Dessa vez peço encarecidamente que **não esqueçam de colocar o tempo das suas talks!**

Basta seguir o template de resposta ao responder essa issue.

Como mencionado no `README.md`, o pessoal vai votar usando 👍 e ❤️ será o critério de desempate.

**Serão bem vindas tanto Lightning Talks quanto talks de maior duração.** Não importa qual sua duração, poste nessa issue para podermos organizar o tempo e fazer um schedule.

E não tenham medo, submetam, sempre queremos ouvir o que vocês têm pra falar!

**Comment by filipi87** [comment]
# Web Components

### Abstract

Desmistificando os Web Components, visão geral, ciclo de vida, benefícios e riscos.
Benefícios da utilização da biblioteca Polymer.
Experiências adquiridas durante 01 ano e meio de utilização em produção:
   - Organização da documentação;
   - Testes automatizados;
   - Fluxo para criação de novos componentes;

### Duração

30 minutos.

**Comment by douglaseel** [comment]
# Desmistificando o WebRTC: _peer-to-many_

## Abstract
Explorando o WebRTC, visão geral, propósito de sua utilização e caso de uso em soluções _peer-to-many_.
Comparativo das arquiteturas Mesh, MCU e SFU:
* Prós, contras e melhor aplicação.

Experiências obtidas na utilização de WebRTC para soluções de videoconferência.

## Duração
50 minutos.

**Comment by marcosvlehmkuhl** [comment]
# Programação Funcional em JavaScript usando Ramda

### Abstract

Uma introdução à conceitos de programação funcional usando a biblioteca Ramda.

### Duração

20 minutos.

**Comment by douglaseel** [comment]
# React Native na Dígitro

## Abstract
Introdução e visão geral do React Native. 
Experiência de caso de uso do React Native na Dígitro.

## Duração
20 minutos.

**Comment by diogomoretti** [comment]
Obrigado a todos pelos envios =]
