### ISSUE TITLE
Talk sobre Web Components

### ISSUE THREAD

**Issue by filipi87** [floripajs/talks#3]
# Web Components

### Abstract

Desmistificando os Web Components, visão geral, ciclo de vida, benefícios e riscos.
Benefícios da utilização da biblioteca Polymer.
Experiências adquiridas durante 01 ano e meio de utilização em produção:
   - Organização da documentação;
   - Testes automatizados;
   - Fluxo para criação de novos componentes;

### Duração

30 minutos.

**Comment by lucasfcosta** [comment]
Oi @filipi87, tudo bem?

Gostei muito da sua talk, parece bem interessante e você preencheu certinho todos os campos.

Você poderia postar isso na issue #2? Assim conseguimos manter todas as sugestões em uma issue só.

**Muito obrigado pela colaboração!**

**Comment by diogomoretti** [comment]
Valeu @filipi87 =] Vou fechar essa aqui ;)
