### ISSUE TITLE
Talk sobre programação funcional e Ramda

### ISSUE THREAD

**Issue by marcosvlehmkuhl** [floripajs/talks#5]
# Programação Funcional em JavaScript usando Ramda

### Abstract

Uma introdução à conceitos de programação funcional usando a biblioteca Ramda.

### Duração

20 minutos.

**Comment by EdemarSantos** [comment]
Legal, @marcosvlehmkuhl ! Pelo que entendi, o @lucasfcosta quer que todos postem na issue #2 . Podes fazê-lo? Valeu!

**Comment by marcosvlehmkuhl** [comment]
Viajei aqui, valeu :)
