### ISSUE TITLE
#17 FloripaJS Devs Meetup – CIASC

### ISSUE THREAD

**Issue by lucasfcosta** [floripajs/talks#6]
E aí pessoal! **Está aberto o Call for Papers para as talks do próximo FloripaJS!**

Dessa vez peço encarecidamente que **não esqueçam de colocar o tempo das suas talks!**

Basta seguir o template de resposta ao responder essa issue.

```
# [Título da sua talk (OBRIGATÓRIO)]

### Abstract

[Um parágrafo resumindo o conteúdo geral da sua talk. (OBRIGATÓRIO)]

### Descrição

[Uma descrição mais detalhada do que você vai falar, como vai ser seu approach ao assunto e coisas do tipo. (OPCIONAL)]

### Duração

[Tempo aproximado de duração da sua talk. (OBRIGATÓRIO)]

[Obs.: Não importa quanto tempo seja, desde que possua menos de 50/60 minutos. Encaixaremos as talks conforme a disponibilidade do horário.]

### Comentários

[Seus comentários sobre essa submissão. O motivo pelo qual você quer falar sobre isso ou o motivo pelo qual esse assunto é interessante. Enfim, tudo mais que você quiser falar. (OPCIONAL)]

```

-------------------

Como mencionado no `README.md`, o pessoal vai votar usando 👍 e ❤️ será o critério de desempate.

**Serão bem vindas tanto Lightning Talks quanto talks de maior duração.** Não importa qual sua duração, poste nessa issue para podermos organizar o tempo e fazer um schedule.

E não tenham medo, submetam, sempre queremos ouvir o que vocês têm pra falar!

**Comment by vieiralucas** [comment]
# Building a lazy map function using Proxies
### Abstract

Nesta talk iremos implementar uma função [map](https://lodash.com/docs/4.17.4#map) preguiçosa usando o poder dos [Proxies](https://ponyfoo.com/articles/es6-proxies-in-depth)

### Descrição

Irei explicar como funciona os Proxies e depois iremos direto pro ❤️ VIM ❤️ botar a mão na massa
### Duração

Ainda preciso medir, mas estou imaginando uns 30 minutos.

### Comentários

Espero que você aprenda algumas técnicas e ideias de _functional programming_, alem de ver uma aplicação prática de Proxies 😄

**Comment by cotts** [comment]
# [Training Center - Uma comunidade para quem quer aprender e ensinar]

### Abstract

Irei apresentar para os participantes sobre a comunidade Training Center

### Descrição

Será apresentada a Comunidade Training Center e seus principais projetos, como a Mentoria, projetos de estudos, eventos e parcerias. Para quem quer aprender e também para quem gosta de ensinar.

### Duração

Max: 20 min

### Comentários

Como participante da comunidade e também novo no mundo do desenvolvimento, esta comunidade está sendo muito boa na  evolução do meu conhecimento e espero que seja boa para vocês também!

**Comment by felpin** [comment]
# Liberando o poder do aggregation framework do MongoDB no Node

### Abstract

Irei apresentar sobre o aggregation framework do MongoDB e como utilizá-lo no Node

### Descrição

Farei uma introdução ao MongoDB, mostrando algumas diferenças entre o NoSQL e o SQL. Após um boa introdução, vou explicar rapidamente como conectar sua aplicação em um banco de dados do mongo, seja utilizando o driver oficial ou o mongoose.
Depois mostrarei o que é o aggregation framework, como ele funciona e quais as suas funções(match, project, unwind, group etc.).

### Duração

Introdução ao MongoDB (+- 10 min)
Como utilizar o MongoDB no Node (+- 5 min)
Aggregation Framework (+- 15 min)

**Comment by cotts** [comment]
Pessoal, infelizmente vou cancelar minha talk... vai ficar para uma próxima

**Comment by sergiofm** [comment]
# Descomplicando as normas da ABNT com JS

### Abstract

Um overview da arquitetura do Mettzer.

### Descrição

A idéia é mostrar toda a arquitetura do Mettzer e falar sobre as decisões de projeto e o porque de cada escolha. Também pretendo falar sobre as lições aprendidas e os desafios que estão por vir. No final, a idéia era ter um bom tempo para perguntas e discussão sobre o que pode ser melhorado e etc.

### Duração

[Tempo aproximado de duração da sua talk. (OBRIGATÓRIO)]

Ainda nem montei a palestra, mas minha idéia é que ela fique entre 30 e 40 minutos.

### Comentários

O principal motivo é colocar a arquitetura do Mettzer ao crivo da gelera, e também mostrar pro pessoal com menos experiência o quanto pode ser complexo ter uma aplicação JS em produção.

**Comment by brnluiz** [comment]
# Uma alternativa ao GitFlow

### Abstract

O GitFlow foi criado em 2010 pelo Vincent Driessen. Desde então, diversas empresas já puderam testar e implementar, o que possibilitou que o mercado trouxesse alguns feedbacks de quão bem, ou não, ele funciona. Nessas iterações alguns modelos mais simples surgiram e esse talk se propõe a demonstrar isso, junto com o workflow de projeto utilizado hoje no time em que trabalho.

### Duração

Ainda não mensurei, porém provavelmente ficará entre 15-30 minutos (atualizo aqui assim que possuir uma estimativa mais precisa)

### Comentários

Pretendo mostrar conceitualmente como funciona e organizar uma demonstração básica

**Comment by marquinhoalm** [comment]
## Mantendo o histórico do GIT lindo ❤️
### Idéia
Demonstrar como podemos deixar um histórico de commits sano, após a fase de desenvolvimento para acabar com N commits de *fix* (exemplo) entre outras situações que surge enquanto você está fazendo sua tarefa,  juntar commits que tenham o mesmo sentido e algumas outras situações que acontecem.
### Duração
_20-30 minutos_

**Comment by cotts** [comment]
Pessoal, seguem fotos tiradas no FloripaJS #17

/dist (fotosCompactadas)
https://goo.gl/photos/fik4275e2Yr5RUpT7

/src (fotosTamanhoOriginal)
https://goo.gl/photos/6DRqFDX9UeZmvQCZA
