### ISSUE TITLE
#18 FloripaJS Devs Meetup – Auditório ACATE

### ISSUE THREAD

**Issue by lucasfcosta** [floripajs/talks#7]
E aí pessoal! **Está aberto o Call for Papers para as talks do próximo FloripaJS!**

Dessa vez peço encarecidamente que **não esqueçam de colocar o tempo das suas talks!**

Basta seguir o template de resposta ao responder essa issue.

```
# [Título da sua talk (OBRIGATÓRIO)]

### Abstract

[Um parágrafo resumindo o conteúdo geral da sua talk. (OBRIGATÓRIO)]

### Descrição

[Uma descrição mais detalhada do que você vai falar, como vai ser seu approach ao assunto e coisas do tipo. (OPCIONAL)]

### Duração

[Tempo aproximado de duração da sua talk. (OBRIGATÓRIO)]

[Obs.: Não importa quanto tempo seja, desde que possua menos de 50/60 minutos. Encaixaremos as talks conforme a disponibilidade do horário.]

### Comentários

[Seus comentários sobre essa submissão. O motivo pelo qual você quer falar sobre isso ou o motivo pelo qual esse assunto é interessante. Enfim, tudo mais que você quiser falar. (OPCIONAL)]

```

-------------------

Como mencionado no `README.md`, o pessoal vai votar usando 👍 e ❤️ será o critério de desempate.

**Serão bem vindas tanto Lightning Talks quanto talks de maior duração.** Não importa qual sua duração, poste nessa issue para podermos organizar o tempo e fazer um schedule.

E não tenham medo, submetam, sempre queremos ouvir o que vocês têm pra falar!

**Comment by welitonderesende** [comment]
# Web animations 

### Abstract

Web animations são cada vez mais frequentes em interfaces na web, além de agradáveis elas tem um papel muito importante para a experiência do usuário, vamos falar um pouco sobre os conceitos e como implementá-las com css e js!

### Duração
25 minutos

### Comentários

Gente, web animations são bastante importantes para facilitar a compreensão das ações à serem tomadas pelo usuário e também deixar a interface mais agradável e convidativa, acredito que principalmente para front-enders, fazer uso ou ter conhecimento delas é bem legal. :D

**Comment by bateramos** [comment]
# Algoritmo genético para simulação de reentrada em queda livre na atmosfera usando JS

### Abstract

Demo e explicação do que seria um algoritmo genético, diferença entre esse tipo de IA e outras opções, passando pelo principais conceitos para se utilizar esse tipo de algoritmo.

### Duração

45 minutos

### Comentários

Irei demonstrar um projeto pessoal, acho que o mais importante é compartilhar o conhecimento adquirito com a comunidade e corrigir qualquer equivoco que eu tenha cometido no meu aprendizado.

repo: https://github.com/bateramos/GeneticLander (em desenvolvimento =b)

**Comment by viniciuskneves** [comment]
# Como o Javascript funciona

### Abstract

Explicação de forma geral como o Javascript funciona por baixo dos panos e algumas técnicas que podem impactar na performance do seu código.

### Descrição

O foco são as pessoas novas na linguagem, mas também serve como um refresh para os mais experientes, já que não é algo que se vê ou discute todos os dias. Vou apresentar o que é Call Stack e Memory Heap, que são a base do Javascript e em sequência introduzir onde que o ambiente (Engine) se faz presente e o que ele adiciona nesse contexto, como Event Loop, Callback Queue e APIs externas. Por fim vou comentar de algumas dicas que podem influenciar no desempenho de um código Javascript.

### Duração

20-25 minutos

### Comentários

Entender o básico, como a linguagem funciona por baixo dos panos, auxilia o desenvolvedor na hora de analisar o código que está escrevendo ou ainda a entender comportamentos estranhos (bugs) na execução do mesmo. Sei que existe bastante material de qualidade a respeito disso na web, porém a ideia é apresentar para quem está entrando nesse mundo alguns nomes e termos que eles vão encontrar pela frente.

**Comment by viniciuskneves** [comment]
# Como tratar múltiplos JSONPs com o mesmo callback name?

### Abstract

Usar uma API que suporta JSONP porém que não suporta customização no nome do callback pode se tornar uma grande dor de cabeça. Aqui apresento como cheguei a uma solução para esse problema e coloquei em produção onde trabalho.

### Descrição

JSONP já é um velho conhecido da web, portanto o foco não é explicar o que é JSONP. A ideia é unir JSONP com iframes e resolver um problema real, no qual um cliente não quis solucionar do lado dele.

### Duração

15-20 minutos

### Comentários

Existe um post meu no medium falando disso (https://medium.com/@viniciuskiatkoskineves/handling-a-jsonp-nightmare-3865c9d8bfdd) que será a base da apresentação. Já apresentei isso internamente na empresa uma vez, e serve como uma alternativa para minha submissão anterior (Como o Javascript funciona).

**Comment by diogomoretti** [comment]
Vamos fechar a issue já que foram 3 envios certinho =]

**Comment by diogomoretti** [comment]
Podemos confirmar vocês para amanhã @welitonderesende, @bateramos e @viniciuskneves?
