### ISSUE TITLE
#19 FloripaJS Devs Meetup - Involves

### ISSUE THREAD

**Issue by marquinhoalm** [floripajs/talks#8]
E aí pessoal! Está aberto o Call for Papers para as talks do próximo FloripaJS!

Dessa vez peço encarecidamente que não esqueçam de colocar o tempo das suas talks!

EDIT: **Nesta edição teremos a escolha de *(2) duas* talks. A *(3) terceira* ficará por conta de um integrante da empresa sede!**

Basta seguir o template de resposta ao responder essa issue.

```
# [Título da sua talk (OBRIGATÓRIO)]

### Abstract

[Um parágrafo resumindo o conteúdo geral da sua talk. (OBRIGATÓRIO)]

### Descrição

[Uma descrição mais detalhada do que você vai falar, como vai ser seu approach ao assunto e coisas do tipo. (OPCIONAL)]

### Duração

[Tempo aproximado de duração da sua talk. (OBRIGATÓRIO)]

[Obs.: Não importa quanto tempo seja, desde que possua menos de 50/60 minutos. Encaixaremos as talks conforme a disponibilidade do horário.]

### Comentários

[Seus comentários sobre essa submissão. O motivo pelo qual você quer falar sobre isso ou o motivo pelo qual esse assunto é interessante. Enfim, tudo mais que você quiser falar. (OPCIONAL)]
```

### Datas
**Prazo para envio:** 13/Fev/2018 - 23h
**Divulgação das talks aprovadas:** 14/Fev/2018 - 15h

**Comment by klarkc** [comment]
# Componentes: Stateful x Stateless? Dumb x Smart?

### Abstract

Irei abordar as diferenças entre esses tipos de componentes e como eles se relacionam entre si.

### Descrição

Vou iniciar mostrando diferenças entre funções puras e impuras, e a partir daí, usarei exemplos do Vue e Vuex (bibliotecas que estou mais habituado), porém os conceitos abordados podem ser aplicados a qualquer lib ou framework. Na finalização apresentarei alguns cenários reais e quais decisões de abordagem foram feitas para esses cenários.

### Duração

30 minutos.

### Comentários

Acho legal, até pouco tempo eu mesmo não sabia diferenciar, e ouvia esses termos sem compreender com exatidão o que significam. Saber essas diferenças ajuda a pensar e organizar melhor a arquitetura de um sistema em desenvolvimento.

**Comment by vieiralucas** [comment]
# webpack de uma vez por todas

### Abstract

Você já escreveu um webpack file do zero? Você sabe como o webpack funciona? Irei mostrar que não tem magia e vamos entender o webpack de uma vez por todas.

### Descrição

TODO

### Duração

TODO

### Comentários

Vou pensar mais ainda em como vai ser a talk em si e ver quanto tempo vai levar.

**Comment by LucasLeandro1204** [comment]
# Web-scraping

### Abstract

Nem sempre um site oferece uma API, seja um site de notícias, fotos, etc. Vou ensinar como criar um service para capturar os dados desejados.

### Descrição

De primeira vou apresentar a lib que será usada para extrair os dados, assim como outras soluções e comparações. Logo após irei pegar uma aplicação simples já pronta, ela vai ser responsável por exibir os dados que iremos pegar.

### Duração

30 - 40 min

### Comentários

Vou mostrar como fazer scrap de um site estático, mas na talk irei mostrar soluções para extrair dados de um SPA também. Ainda falta escolher qual site vou usar de exemplo e a mini-aplicação pra exibir os dados.

**Comment by Strapazzon** [comment]
#  Quais as novidades do Angular v5? Temos mais novidades na v6 ? Angular5/6 , VueJS ou ReactRedux? 

### Abstract
Irei apresentar algumas novidades a respeito do Angular 5 e o que já está disponível na v6.0.0.beta.2. 

### Descrição

- Vamos abordar as novidades que já estão disponíveis na v5 e v6.beta, uma demonstração do CLI do angular que vem se tornando mais completo e customizável a cada nova versão. 
- Um Benchmark entre Angular5 , VueJS e ReactRedux.
- Alguns pontos Fortes/Fracos de cada uma das Frameworks. 


### Duração

50 minutos. 

### Comentários

Essa apresentação é baseada em um caso de estudos que foi realizado na empresa SocialBase para migração de um projeto AngularJS, onde foram levantados vários pontos fortes e fracos dessas frameworks, e optamos por uma delas.

**Comment by brunosfreitas** [comment]
# Fast Talk: Ferramentas de design para não designers

## Abstract

Não sabe diferenciar vermelho de magenta? Está na dúvida do porque Comic Sans não fica bom com Times New Roman? Porque diabos o cliente quer o site dele marrom? O Designer do time (que nem existe, porque a grana está curta) foi viajar? Como resolver, ou pelo menos ter para onde correr, nessas horas?

## Descrição
* A ideia é apresentar algumas ferramentas e sites que podem agilizar todo esse processo.
* O que não fazer, ou pelo menos tentar evitar, durante a montagem do seu sistema.

## Duração

20 minutos.

## Comentários

Desperte o designer dentro de você! Essa apresentação serve como base para qualquer um que deseja aprender uma base mínima sobre design prático, não sendo focada somente para devs.

**Comment by marquinhoalm** [comment]
Amigos... Está encerrada a inclusão de novas talks. Agradeço a todos pelo envio =)
